Get all tests to pass locally with no special configuration
AI-Hypercomputer/maxtext pull request #1108
Opened 2024-12-19 23:53 UTC by SamuelMarks

# Description

FIXES: #1107

# Tests

`python -m pytest` and `pytest` should both now work when run from repository root.

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run end-to-end tests tests and provided workload links above if applicable.
- [x] I have made or will make corresponding changes to the doc if needed.

---

Important: do not merge yet! - I want to solve your grain issue [https://github.com/AI-Hypercomputer/maxtext/actions/runs/12421511705/job/34681866302] first; which I think this commit fixed https://github.com/google/grain/compare/ce66a97aa88cc4618001ca9ba80c119178f8af4a...08f7cb175da8ae3c150027500a47797a8f9ddd6c

2024-12-20 18:22 UTC, shralex commented
The grain issue might be solved by https://github.com/AI-Hypercomputer/maxtext/pull/1109

2024-12-20 18:25 UTC, SamuelMarks commented
Good to see. Also related is your recent PR #1113

2025-02-19 18:34 UTC, shralex commented
Hi @SamuelMarks sorry for the delay! Do you have time to update the PR so we can merge it ? New tests might have been added (in particular some integration tests).

2025-03-06 11:07 UTC, shralex approved these changes
Thank you Samuel!!

2025-03-20 16:42 UTC, gobbleturk approved these changes

2025-03-24 21:26 UTC, gobbleturk requested changes
This is a pretty big PR that is difficult for us to merge.

Could you break this PR into smaller chunks? I see some of the changes here are style / typo / variable name improvements, perhaps we could start with a smaller PR that is only those? Some of those are using `os.join()` which we do prefer wherever possible (I'm not sure if we may need the larger module change first to use PKG_ROOT or if you could include these changes in an intial cleanup PR)

2025-03-25 03:43 UTC, SamuelMarks commented on MaxText/layers/models.py
> +  pipeline_module: pipeline.Pipeline
Linter errors

2025-03-25 03:43 UTC, SamuelMarks commented on MaxText/decode.py
> -def main(argv: Sequence[str]) -> None:
Linter errors; elsewhere you have a `[None, '', '']`

2025-03-25 03:45 UTC, SamuelMarks commented on MaxText/configs/a3/llama_2_7b/16vm.sh
> -export EXECUTABLE="train.py"
Module name, so the oft seen `python3 -m http.server` would be:
```sh
export EXECUTABLE='server'
python3 -m http."${EXECUTABLE}"
```

2025-03-25 03:53 UTC, SamuelMarks commented
> This is a pretty big PR that is difficult for us to merge. However it looks awesome and all the changes look great
> 
> Could you break this PR into smaller chunks? I see some of the changes here are style / typo / variable name improvements, perhaps we could start with a smaller PR that is only those? Some of those are using `os.join()` which we do prefer wherever possible (I'm not sure if we may need the larger module change first to use PKG_ROOT or if you could include these changes in an intial cleanup PR)

I can try to split this into smaller chunks; but want to move quickly on this and would prefer not to separate out the linter fixes—like changing import orders—from the move to a proper Python package layout. Similarly the `PKG_ROOT` addition from today helps keep everything properly relative to the correct directory; combined with `os.path` this enables basically the whole Python package to be relocatable… with the exception of things outside the root like `benchmarks`. How about **splitting by module** rather than per lint-fix/python-package/os.path/misc. fixes?

Once the contents of this PR is merged the whole of maxtext should be `pip install`able. Then for future work we can thing about uploading to pypi and associating it with a [generated HTML] documentation site.

(might also be worth looking at related projects like maxdiffusion and extraction out a common [`pip install`able] shared library betwixt the two)

2025-03-25 03:53 UTC, SamuelMarks commented
> This is a pretty big PR that is difficult for us to merge. However it looks awesome and all the changes look great
> 
> Could you break this PR into smaller chunks? I see some of the changes here are style / typo / variable name improvements, perhaps we could start with a smaller PR that is only those? Some of those are using `os.join()` which we do prefer wherever possible (I'm not sure if we may need the larger module change first to use PKG_ROOT or if you could include these changes in an intial cleanup PR)

I can try to split this into smaller chunks; but want to move quickly on this and would prefer not to separate out the linter fixes—like changing import orders—from the move to a proper Python package layout. Similarly the `PKG_ROOT` addition from today helps keep everything properly relative to the correct directory; combined with `os.path` this enables basically the whole Python package to be relocatable… with the exception of things outside the root like `benchmarks`. @gobbleturk How about **splitting by module** rather than per lint-fix/python-package/os.path/misc. fixes?

Once the contents of this PR is merged the whole of maxtext should be `pip install`able. Then for future work we can thing about uploading to pypi and associating it with a [generated HTML] documentation site.

(might also be worth looking at related projects like maxdiffusion and extraction out a common [`pip install`able] shared library betwixt the two)

2025-03-25 03:55 UTC, SamuelMarks commented
> This is a pretty big PR that is difficult for us to merge. However it looks awesome and all the changes look great
> 
> Could you break this PR into smaller chunks? I see some of the changes here are style / typo / variable name improvements, perhaps we could start with a smaller PR that is only those? Some of those are using `os.join()` which we do prefer wherever possible (I'm not sure if we may need the larger module change first to use PKG_ROOT or if you could include these changes in an intial cleanup PR)

I can try to split this into smaller chunks; but want to move quickly on this and would prefer not to separate out the linter fixes—like changing import orders—from the move to a proper Python package layout. Similarly the `PKG_ROOT` addition from today helps keep everything properly relative to the correct directory; combined with `os.path` this enables basically the whole Python package to be relocatable… with the exception of things outside the root like `benchmarks`. @gobbleturk How about **splitting by module** rather than per lint-fix/python-package/os.path/misc. fixes?

Once the contents of this PR is merged the whole of maxtext should be `pip install`able. Then for future work one can think about uploading to pypi and associating it with a [generated HTML] documentation site.

(might also be worth looking at related projects like maxdiffusion and extraction out a common [`pip install`able] shared library betwixt the two)

2025-03-25 21:35 UTC, gobbleturk commented
> > This is a pretty big PR that is difficult for us to merge. However it looks awesome and all the changes look great
> > Could you break this PR into smaller chunks? I see some of the changes here are style / typo / variable name improvements, perhaps we could start with a smaller PR that is only those? Some of those are using `os.join()` which we do prefer wherever possible (I'm not sure if we may need the larger module change first to use PKG_ROOT or if you could include these changes in an intial cleanup PR)
> 
> I can try to split this into smaller chunks; but want to move quickly on this and would prefer not to separate out the linter fixes—like changing import orders—from the move to a proper Python package layout. Similarly the `PKG_ROOT` addition from today helps keep everything properly relative to the correct directory; combined with `os.path` this enables basically the whole Python package to be relocatable… with the exception of things outside the root like `benchmarks`. @gobbleturk How about **splitting by module** rather than per lint-fix/python-package/os.path/misc. fixes?
> 
> Once the contents of this PR is merged the whole of maxtext should be `pip install`able. Then for future work one can think about uploading to pypi and associating it with a [generated HTML] documentation site.
> 
> (might also be worth looking at related projects like maxdiffusion and extraction out a common [`pip install`able] shared library betwixt the two)

Ah okay this soundsawesome! Yes splitting by module sounds great to me

2025-03-26 01:34 UTC, SamuelMarks commented
Ok, to split this up by module it's time for some one-liner fu!
```sh
fd -Fepy -j1 '__init__' -x bash -c 'd=${0:2}; d=${d//\//.}; git switch main && git checkout -b "PKG-FIX_${d}" && git checkout test-fixer "${0}" && git commit -S -am "[${d}] Python package layout support and minor other fixes" && git push mine "PKG-FIX_${d}" && gh pr create --title "Python package layout support and minor other fixes" --body "For commentary see #1108"' {//}
```

2025-03-26 01:40 UTC, SamuelMarks commented
Ok, to split this up by module it's time for some one-liner fu!
```sh
fd -Fepy -j1 '__init__' -x bash -c 'd=${0:2}; d=${d//\//.}; git switch main && git checkout -b "PKG-FIX_${d}" && git checkout test-fixer "${0}" && git commit -S -am "[${d}] Python package layout support and minor other fixes" && git push mine "PKG-FIX_${d}" && gh pr create --title "[${d}] Python package layout support and minor other fixes" --body "For commentary see #1108"' {//}
```

FYI: These new PRs constitute 71.174377224199288256% of the total files changed in this PR; i.e., 200 files (leaving 81 here). So I recommend not closing this PR; merge the others first; and then this will have a mere soupçon leftover.

2025-04-27 15:24 UTC, shralex commented on MaxText/layers/embeddings.py
> +    return jnp.dot(query, jnp.asarray(self.embedding, jnp.bfloat16).T, preferred_element_type=dtype)
@gobbleturk can you please check if this is something we'd like to do.

2025-04-27 15:24 UTC, shralex commented on MaxText/maxengine.py
>    # batch and cache related
can we move this comment to the list above before max_prefill_predict_length

2025-04-27 15:24 UTC, shralex commented on MaxText/scratch_code/golden_llama3_1_export.py
> +  upload_blob("maxtext-llama", output_path, f"Llama3_1_8B/golden-logits/{output_path}")
can we use an f string for the entire string here, also the next line

2025-04-27 15:24 UTC, shralex commented on MaxText/train.py
> +  # ^ [B, S, E], [B, S, E]
can we put this comment before the previous line

2025-04-27 15:24 UTC, shralex commented on benchmarks/xla_flags_library.py
> +CUSTOM_VMEM_LIMIT_FLAG = "--xla_tpu_scoped_vmem_limit_kib={}".format
Lets revert this, as this isn't always equivalent

2025-04-27 19:23 UTC, SamuelMarks commented on MaxText/input_pipeline/_tfds_data_processing_c4_mlperf.py
> -#   https://github.com/google-research/text-to-text-transfer-transformer/blob/ba171b6f94eafcee60d0714fd6d60749b572d1f2/t5/data/preprocessors.py
Made it fit on one line by using the [Short SHA-1](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#_short_sha_1)

2025-04-27 19:24 UTC, SamuelMarks commented on MaxText/maxengine.py
>    # batch and cache related
Ok

2025-04-27 19:24 UTC, SamuelMarks commented on MaxText/train.py
> +  # ^ [B, S, E], [B, S, E]
Done

2025-04-27 19:28 UTC, SamuelMarks commented on benchmarks/xla_flags_library.py
> +CUSTOM_VMEM_LIMIT_FLAG = "--xla_tpu_scoped_vmem_limit_kib={}".format
Was resolving this lint https://pylint.pycqa.org/en/latest/user_guide/messages/convention/unnecessary-lambda-assignment.html whilst concurrently avoiding adding a trivial function with a docstring. Checked all usages in the codebase and it seems fine. I can replace usages with `xla_flags_library.CUSTOM_VMEM_LIMIT_FLAG(vmem_limit=122880)` and this with `{vmem_limit}".format` if you like…

2025-04-27 19:31 UTC, SamuelMarks commented on MaxText/scratch_code/golden_llama3_1_export.py
> +  upload_blob("maxtext-llama", output_path, f"Llama3_1_8B/golden-logits/{output_path}")
Ok

2025-04-27 22:51 UTC, shralex commented on benchmarks/xla_flags_library.py
> +CUSTOM_VMEM_LIMIT_FLAG = "--xla_tpu_scoped_vmem_limit_kib={}".format
That sounds good, thank you! I believe you might also need to do .format(vmem_limit=vmem_limit_value)

2025-04-28 00:44 UTC, SamuelMarks commented on benchmarks/xla_flags_library.py
> +CUSTOM_VMEM_LIMIT_FLAG = "--xla_tpu_scoped_vmem_limit_kib={}".format
Sure thing: now takes `vmem_limit` keyword argument

2025-04-29 15:59 UTC, gobbleturk commented on MaxText/layers/embeddings.py
> +    return jnp.dot(query, jnp.asarray(self.embedding, jnp.bfloat16).T, preferred_element_type=dtype)
ya this looks good to me

2025-04-29 16:02 UTC, gobbleturk approved these changes

2025-04-29 17:14 UTC, SamuelMarks commented on benchmarks/upload_metrics_to_bq.py
> +  elif options.hardware_id in ("a3mega", "a3ultra", "'a3ultra"):
@raymondzouu I am not sure if this is a typo or if the `'a3ultra` was intended due to a bug lower down the parsing pipeline?

2025-04-29 20:30 UTC, raymondzouu commented on benchmarks/upload_metrics_to_bq.py
> +  elif options.hardware_id in ("a3mega", "a3ultra", "'a3ultra"):
Thanks for finding this, yeah this is a type and should just be `a3ultra`

2025-04-30 03:45 UTC, merged